//! USTX project export rendering.
//!
//! This module mirrors the deterministic `save_ustx(..., rmvpe_result=None)`
//! project export path in `inference/API/ustx_api.py`. Python remains the
//! runtime owner for filesystem writes, warning output, and pitch curves.

/// One note row accepted by the USTX project renderer.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct UstxNoteInfo<'a> {
    pub onset: f64,
    pub offset: f64,
    pub pitch: f64,
    pub lyric: &'a str,
}

/// Rendered USTX project YAML plus the number of invalid input notes skipped.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UstxProjectExport {
    pub yaml: String,
    pub skipped_invalid_notes: usize,
}

/// Recoverable USTX rendering failures at the Rust library boundary.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum UstxProjectError {
    InvalidTempo,
    TickOutOfRange,
}

/// Renders Python-compatible USTX project YAML for `rmvpe_result=None`.
///
/// # Errors
///
/// Returns an error when `tempo` is non-finite or when tick conversion would
/// exceed the supported integer range.
pub fn render_ustx_project(
    notes: &[UstxNoteInfo<'_>],
    project_name: &str,
    tempo: f64,
) -> Result<UstxProjectExport, UstxProjectError> {
    if !tempo.is_finite() {
        return Err(UstxProjectError::InvalidTempo);
    }

    let mut skipped_invalid_notes = 0usize;
    let mut valid_notes = Vec::new();
    for note in notes {
        if is_valid_note(note) {
            valid_notes.push(*note);
        } else {
            skipped_invalid_notes += 1;
        }
    }
    valid_notes.sort_by(|left, right| left.onset.partial_cmp(&right.onset).unwrap());

    let rendered_notes = valid_notes
        .iter()
        .map(|note| render_note(note, tempo))
        .collect::<Result<Vec<_>, _>>()?;
    let max_end_tick = rendered_notes
        .iter()
        .map(|note| note.position + note.duration)
        .max()
        .unwrap_or(0);
    let voice_part_duration = 480.max(max_end_tick);

    let tempo_text = python_float_repr(tempo);
    let mut yaml = String::new();
    yaml.push_str("name: ");
    yaml.push_str(&yaml_scalar(project_name, 0));
    yaml.push('\n');
    yaml.push_str(
        "comment: Generated by Vocal2Midi\n\
output_dir: Vocal\n\
cache_dir: UCache\n\
ustx_version: '0.7'\n\
resolution: 480\n\
bpm: ",
    );
    yaml.push_str(&tempo_text);
    yaml.push('\n');
    yaml.push_str(STATIC_PROJECT_BODY);
    yaml.push_str("tempos:\n- position: 0\n  bpm: ");
    yaml.push_str(&tempo_text);
    yaml.push('\n');
    yaml.push_str(TRACKS_YAML);
    yaml.push_str("voice_parts:\n- duration: ");
    yaml.push_str(&voice_part_duration.to_string());
    yaml.push_str("\n  name: ");
    yaml.push_str(&yaml_scalar(project_name, 2));
    yaml.push_str(
        r#"
  comment: ''
  track_no: 0
  position: 0
"#,
    );
    if rendered_notes.is_empty() {
        yaml.push_str("  notes: []\n");
    } else {
        yaml.push_str("  notes:\n");
        for note in &rendered_notes {
            append_note_yaml(&mut yaml, note);
        }
    }
    yaml.push_str("  curves: []\nwave_parts: []\n");

    Ok(UstxProjectExport {
        yaml,
        skipped_invalid_notes,
    })
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct RenderedNote<'a> {
    position: i64,
    duration: i64,
    tone: u8,
    lyric: &'a str,
}

fn render_note<'a>(
    note: &UstxNoteInfo<'a>,
    tempo: f64,
) -> Result<RenderedNote<'a>, UstxProjectError> {
    let position = to_ticks(note.onset, tempo)?;
    let end = to_ticks(note.offset, tempo)?;
    let duration = 10.max(end - position);
    Ok(RenderedNote {
        position,
        duration,
        tone: clamp_tone(note.pitch),
        lyric: if note.lyric.is_empty() {
            "a"
        } else {
            note.lyric
        },
    })
}

fn append_note_yaml(output: &mut String, note: &RenderedNote<'_>) {
    output.push_str("  - position: ");
    output.push_str(&note.position.to_string());
    output.push_str("\n    duration: ");
    output.push_str(&note.duration.to_string());
    output.push_str("\n    tone: ");
    output.push_str(&note.tone.to_string());
    output.push_str("\n    lyric: ");
    output.push_str(&yaml_scalar(note.lyric, 4));
    output.push_str(NOTE_SUFFIX_YAML);
}

fn is_valid_note(note: &UstxNoteInfo<'_>) -> bool {
    note.onset.is_finite()
        && note.offset.is_finite()
        && note.pitch.is_finite()
        && note.offset > note.onset
}

fn to_ticks(seconds: f64, tempo: f64) -> Result<i64, UstxProjectError> {
    round_half_even_i64(seconds * tempo * 8.0)
}

fn clamp_tone(pitch: f64) -> u8 {
    if pitch <= 0.0 {
        0
    } else if pitch >= 127.0 {
        127
    } else {
        round_half_even_i64(pitch).unwrap_or(0).clamp(0, 127) as u8
    }
}

fn round_half_even_i64(value: f64) -> Result<i64, UstxProjectError> {
    if !value.is_finite() || value < i64::MIN as f64 || value > i64::MAX as f64 {
        return Err(UstxProjectError::TickOutOfRange);
    }

    let floor = value.floor();
    let diff = value - floor;
    let rounded = if diff < 0.5 {
        floor
    } else if diff > 0.5 {
        floor + 1.0
    } else if (floor as i128).rem_euclid(2) == 0 {
        floor
    } else {
        floor + 1.0
    };
    Ok(rounded as i64)
}

fn python_float_repr(value: f64) -> String {
    let text = format!("{value:?}");
    let Some(exponent_index) = text.find(['e', 'E']) else {
        return text;
    };

    let mut mantissa = text[..exponent_index].to_string();
    if !mantissa.contains('.') {
        mantissa.push_str(".0");
    }

    let exponent = &text[exponent_index + 1..];
    let (sign, digits) = match exponent.as_bytes().first() {
        Some(b'+') => ('+', &exponent[1..]),
        Some(b'-') => ('-', &exponent[1..]),
        _ => ('+', exponent),
    };
    let padded_digits = if digits.len() == 1 {
        format!("0{digits}")
    } else {
        digits.to_string()
    };

    format!("{mantissa}e{sign}{padded_digits}")
}

fn yaml_scalar(value: &str, key_indent: usize) -> String {
    if value.is_empty() {
        return "''".to_string();
    }

    if needs_double_quoted_scalar(value) {
        return double_quoted_scalar(value);
    }

    if value.contains('\n') {
        return multiline_single_quoted_scalar(value, key_indent);
    }

    if needs_single_quoted_scalar(value) {
        return single_quoted_scalar(value);
    }

    value.to_string()
}

fn single_quoted_scalar(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn multiline_single_quoted_scalar(value: &str, key_indent: usize) -> String {
    let continuation_indent = " ".repeat(key_indent + 2);
    let escaped = value.replace('\'', "''");
    let folded = escaped.replace('\n', &format!("\n\n{continuation_indent}"));
    format!("'{folded}'")
}

fn needs_double_quoted_scalar(value: &str) -> bool {
    value.chars().any(|ch| ch != '\n' && ch.is_ascii_control())
}

fn double_quoted_scalar(value: &str) -> String {
    let mut output = String::with_capacity(value.len() + 2);
    output.push('"');
    for ch in value.chars() {
        match ch {
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            '\0' => output.push_str("\\0"),
            '\u{07}' => output.push_str("\\a"),
            '\u{08}' => output.push_str("\\b"),
            '\t' => output.push_str("\\t"),
            '\n' => output.push_str("\\n"),
            '\u{0b}' => output.push_str("\\v"),
            '\u{0c}' => output.push_str("\\f"),
            '\r' => output.push_str("\\r"),
            '\u{1b}' => output.push_str("\\e"),
            ch if ch.is_ascii_control() => {
                output.push_str(&format!("\\x{:02X}", ch as u32));
            }
            _ => output.push(ch),
        }
    }
    output.push('"');
    output
}

fn needs_single_quoted_scalar(value: &str) -> bool {
    if value != value.trim() {
        return true;
    }

    let lower = value.to_ascii_lowercase();
    if matches!(
        lower.as_str(),
        "y" | "yes"
            | "n"
            | "no"
            | "true"
            | "false"
            | "on"
            | "off"
            | "null"
            | "~"
            | ".nan"
            | ".inf"
            | "-.inf"
            | "+.inf"
    ) {
        return true;
    }

    let first = value.as_bytes()[0];
    if matches!(
        first,
        b'#' | b'['
            | b']'
            | b'{'
            | b'}'
            | b'!'
            | b'&'
            | b'*'
            | b'|'
            | b'>'
            | b'@'
            | b'`'
            | b'%'
            | b','
    ) {
        return true;
    }

    if value == "-"
        || value == "?"
        || value.ends_with(':')
        || value.contains(": ")
        || value.contains(" #")
        || value.starts_with("- ")
        || value.starts_with("? ")
    {
        return true;
    }

    if looks_like_yaml_number(value) || looks_like_yaml_date(value) || looks_like_yaml_time(value) {
        return true;
    }

    false
}

fn looks_like_yaml_number(value: &str) -> bool {
    looks_like_yaml_int(value) || looks_like_yaml_float(value)
}

fn looks_like_yaml_int(value: &str) -> bool {
    let bytes = value.as_bytes();
    let mut start = 0usize;
    if matches!(bytes[0], b'+' | b'-') {
        if bytes.len() == 1 {
            return true;
        }
        start = 1;
    }

    let unsigned = &bytes[start..];
    if unsigned.starts_with(b"0b") || unsigned.starts_with(b"0B") {
        return unsigned.len() > 2
            && unsigned[2..]
                .iter()
                .all(|byte| matches!(byte, b'0' | b'1' | b'_'));
    }

    if bytes[start..].starts_with(b"0x") || bytes[start..].starts_with(b"0X") {
        return !bytes[start + 2..].is_empty()
            && bytes[start + 2..]
                .iter()
                .all(|byte| byte.is_ascii_hexdigit() || *byte == b'_');
    }

    if looks_like_yaml_sexagesimal(value) {
        return true;
    }

    if unsigned.len() > 1 && unsigned[0] == b'0' {
        return unsigned[1..]
            .iter()
            .all(|byte| matches!(byte, b'0'..=b'7' | b'_'));
    }

    if unsigned == b"0" {
        return true;
    }

    if !matches!(unsigned.first(), Some(b'1'..=b'9')) {
        return false;
    }

    unsigned
        .iter()
        .all(|byte| byte.is_ascii_digit() || *byte == b'_')
}

fn looks_like_yaml_float(value: &str) -> bool {
    let mut unsigned = value;
    if let Some(stripped) = unsigned
        .strip_prefix('+')
        .or_else(|| unsigned.strip_prefix('-'))
    {
        unsigned = stripped;
    }

    if matches!(
        unsigned,
        ".inf" | ".Inf" | ".INF" | ".nan" | ".NaN" | ".NAN"
    ) {
        return true;
    }

    if looks_like_yaml_sexagesimal_float(unsigned) {
        return true;
    }

    let Some(dot_index) = unsigned.find('.') else {
        return false;
    };

    let (before_dot, after_dot_with_dot) = unsigned.split_at(dot_index);
    let mut after_dot = &after_dot_with_dot[1..];
    let mut exponent = None;
    if let Some(exponent_index) = after_dot.find(['e', 'E']) {
        exponent = Some(&after_dot[exponent_index + 1..]);
        after_dot = &after_dot[..exponent_index];
    }

    let valid_mantissa = if before_dot.is_empty() {
        !after_dot.is_empty()
            && matches!(after_dot.as_bytes().first(), Some(b'0'..=b'9'))
            && after_dot
                .as_bytes()
                .iter()
                .all(|byte| byte.is_ascii_digit() || *byte == b'_')
    } else {
        matches!(before_dot.as_bytes().first(), Some(b'0'..=b'9'))
            && before_dot
                .as_bytes()
                .iter()
                .all(|byte| byte.is_ascii_digit() || *byte == b'_')
            && after_dot
                .as_bytes()
                .iter()
                .all(|byte| byte.is_ascii_digit() || *byte == b'_')
    };
    if !valid_mantissa {
        return false;
    }

    match exponent {
        Some(raw) => {
            let Some(digits) = raw.strip_prefix('+').or_else(|| raw.strip_prefix('-')) else {
                return false;
            };
            !digits.is_empty() && digits.bytes().all(|byte| byte.is_ascii_digit())
        }
        None => true,
    }
}

fn looks_like_yaml_date(value: &str) -> bool {
    let bytes = value.as_bytes();
    bytes.len() == 10
        && bytes[0..4].iter().all(|byte| byte.is_ascii_digit())
        && bytes[4] == b'-'
        && bytes[5..7].iter().all(|byte| byte.is_ascii_digit())
        && bytes[7] == b'-'
        && bytes[8..10].iter().all(|byte| byte.is_ascii_digit())
}

fn looks_like_yaml_time(value: &str) -> bool {
    looks_like_yaml_sexagesimal(value) || looks_like_yaml_sexagesimal_float(value)
}

fn looks_like_yaml_sexagesimal(value: &str) -> bool {
    let mut unsigned = value;
    if let Some(stripped) = unsigned
        .strip_prefix('+')
        .or_else(|| unsigned.strip_prefix('-'))
    {
        unsigned = stripped;
    }

    let Some((head, tail)) = unsigned.split_once(':') else {
        return false;
    };
    if head.is_empty()
        || !matches!(head.as_bytes().first(), Some(b'1'..=b'9'))
        || !head
            .bytes()
            .all(|byte| byte.is_ascii_digit() || byte == b'_')
    {
        return false;
    }

    tail.split(':').all(is_yaml_sexagesimal_group)
}

fn looks_like_yaml_sexagesimal_float(value: &str) -> bool {
    let Some((head, fraction)) = value.rsplit_once('.') else {
        return false;
    };
    looks_like_yaml_sexagesimal(head)
        && !fraction.is_empty()
        && fraction
            .bytes()
            .all(|byte| byte.is_ascii_digit() || byte == b'_')
}

fn is_yaml_sexagesimal_group(value: &str) -> bool {
    if value.is_empty() || value.len() > 2 || !value.bytes().all(|byte| byte.is_ascii_digit()) {
        return false;
    }

    value.parse::<u8>().is_ok_and(|number| number <= 59)
}

const STATIC_PROJECT_BODY: &str = r#"beat_per_bar: 4
beat_unit: 4
expressions:
  dyn:
    name: dynamics
    abbr: dyn
    type: Curve
    min: -240
    max: 120
    default_value: 0
    is_flag: false
  pitd:
    name: pitch deviation
    abbr: pitd
    type: Curve
    min: -1200
    max: 1200
    default_value: 0
    is_flag: false
  clr:
    name: voice color
    abbr: clr
    type: Options
    min: 0
    max: -1
    default_value: 0
    is_flag: false
    options: []
  eng:
    name: resampler engine
    abbr: eng
    type: Options
    min: 0
    max: 1
    default_value: 0
    is_flag: false
    options:
    - ''
    - worldline
  vel:
    name: velocity
    abbr: vel
    type: Numerical
    min: 0
    max: 200
    default_value: 100
    is_flag: false
  vol:
    name: volume
    abbr: vol
    type: Numerical
    min: 0
    max: 200
    default_value: 100
    is_flag: false
  atk:
    name: attack
    abbr: atk
    type: Numerical
    min: 0
    max: 200
    default_value: 100
    is_flag: false
  dec:
    name: decay
    abbr: dec
    type: Numerical
    min: 0
    max: 100
    default_value: 0
    is_flag: false
  gen:
    name: gender
    abbr: gen
    type: Numerical
    min: -100
    max: 100
    default_value: 0
    is_flag: true
    flag: g
  genc:
    name: gender (curve)
    abbr: genc
    type: Curve
    min: -100
    max: 100
    default_value: 0
    is_flag: false
    flag: ''
  bre:
    name: breath
    abbr: bre
    type: Numerical
    min: 0
    max: 100
    default_value: 0
    is_flag: true
    flag: B
  brec:
    name: breathiness (curve)
    abbr: brec
    type: Curve
    min: -100
    max: 100
    default_value: 0
    is_flag: false
    flag: ''
  lpf:
    name: lowpass
    abbr: lpf
    type: Numerical
    min: 0
    max: 100
    default_value: 0
    is_flag: true
    flag: H
  norm:
    name: normalize
    abbr: norm
    type: Numerical
    min: 0
    max: 100
    default_value: 86
    is_flag: true
    flag: P
  mod:
    name: modulation
    abbr: mod
    type: Numerical
    min: 0
    max: 100
    default_value: 0
    is_flag: false
    flag: ''
  mod+:
    name: modulation plus
    abbr: mod+
    type: Numerical
    min: 0
    max: 100
    default_value: 0
    is_flag: false
    flag: ''
  alt:
    name: alternate
    abbr: alt
    type: Numerical
    min: 0
    max: 16
    default_value: 0
    is_flag: false
    flag: ''
  dir:
    name: direct
    abbr: dir
    type: Options
    min: 0
    max: 1
    default_value: 0
    is_flag: false
    options:
    - 'off'
    - 'on'
  shft:
    name: tone shift
    abbr: shft
    type: Numerical
    min: -36
    max: 36
    default_value: 0
    is_flag: false
    flag: ''
  shfc:
    name: tone shift (curve)
    abbr: shfc
    type: Curve
    min: -1200
    max: 1200
    default_value: 0
    is_flag: false
    flag: ''
  tenc:
    name: tension (curve)
    abbr: tenc
    type: Curve
    min: -100
    max: 100
    default_value: 0
    is_flag: false
    flag: ''
  voic:
    name: voicing (curve)
    abbr: voic
    type: Curve
    min: 0
    max: 100
    default_value: 100
    is_flag: false
    flag: ''
exp_selectors:
- dyn
- pitd
- clr
- eng
- vel
- vol
- atk
- dec
- gen
- bre
exp_primary: 0
exp_secondary: 1
key: 0
time_signatures:
- bar_position: 0
  beat_per_bar: 4
  beat_unit: 4
"#;

const TRACKS_YAML: &str = r#"tracks:
- phonemizer: OpenUtau.Core.DefaultPhonemizer
  renderer_settings: {}
  track_name: Track1
  track_color: Blue
  mute: false
  solo: false
  volume: 0
  pan: 0
  track_expressions: []
  voice_color_names:
  - ''
"#;

const NOTE_SUFFIX_YAML: &str = r#"
    pitch:
      data:
      - x: -40.0
        y: 0.0
        shape: io
      - x: 15.0
        y: 0.0
        shape: io
      snap_first: true
    vibrato:
      length: 0
      period: 175
      depth: 25
      in: 10
      out: 10
      shift: 0
      drift: 0
      vol_link: 0
    phoneme_expressions: []
    phoneme_overrides: []
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;
    use std::fs;
    use std::path::PathBuf;

    const FIXTURES: &str = include_str!("../../../../fixtures/ustx_project_export_core.jsonl");

    #[derive(Debug, Clone, PartialEq)]
    struct OwnedNoteInfo {
        onset: f64,
        offset: f64,
        pitch: f64,
        lyric: String,
    }

    impl OwnedNoteInfo {
        fn as_note(&self) -> UstxNoteInfo<'_> {
            UstxNoteInfo {
                onset: self.onset,
                offset: self.offset,
                pitch: self.pitch,
                lyric: &self.lyric,
            }
        }
    }

    fn parse_number(value: &str) -> f64 {
        match value {
            "nan" => f64::NAN,
            "inf" => f64::INFINITY,
            "-inf" => f64::NEG_INFINITY,
            _ => value.parse().unwrap(),
        }
    }

    fn parse_notes(value: &Value) -> Vec<OwnedNoteInfo> {
        value
            .as_array()
            .unwrap()
            .iter()
            .map(|raw_note| OwnedNoteInfo {
                onset: parse_number(raw_note["onset"].as_str().unwrap()),
                offset: parse_number(raw_note["offset"].as_str().unwrap()),
                pitch: parse_number(raw_note["pitch"].as_str().unwrap()),
                lyric: raw_note["lyric"].as_str().unwrap().to_owned(),
            })
            .collect()
    }

    fn fixture_path(repo_relative: &str) -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../../..")
            .join(repo_relative)
    }

    #[test]
    fn ustx_project_export_follows_parity_fixture_table() {
        for (line_index, line) in FIXTURES.lines().enumerate() {
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            let case: Value = serde_json::from_str(line).unwrap();
            let case_id = case["case_id"].as_str().unwrap();
            let owned_notes = parse_notes(&case["notes"]);
            let notes = owned_notes
                .iter()
                .map(OwnedNoteInfo::as_note)
                .collect::<Vec<_>>();
            let expected_yaml =
                fs::read_to_string(fixture_path(case["expected_yaml"].as_str().unwrap())).unwrap();

            let actual = render_ustx_project(
                &notes,
                case["stem"].as_str().unwrap(),
                case["tempo"].as_f64().unwrap(),
            )
            .unwrap();

            assert_eq!(
                actual.skipped_invalid_notes,
                case["skipped_invalid_notes"].as_u64().unwrap() as usize,
                "{case_id} fixture line {} skipped count",
                line_index + 1
            );
            assert_eq!(
                actual.yaml,
                expected_yaml,
                "{case_id} fixture line {} YAML",
                line_index + 1
            );
        }
    }

    #[test]
    fn ustx_project_rejects_non_finite_tempo_without_panicking() {
        assert_eq!(
            render_ustx_project(&[], "bad", f64::NAN).unwrap_err(),
            UstxProjectError::InvalidTempo
        );
    }

    #[test]
    fn yaml_scalar_quotes_legacy_sensitive_words() {
        assert_eq!(yaml_scalar("", 0), "''");
        assert_eq!(yaml_scalar("off", 0), "'off'");
        assert_eq!(yaml_scalar("on", 0), "'on'");
        assert_eq!(yaml_scalar("yes", 0), "'yes'");
        assert_eq!(yaml_scalar("1", 0), "'1'");
        assert_eq!(yaml_scalar("a: b", 0), "'a: b'");
        assert_eq!(yaml_scalar("#tag", 0), "'#tag'");
        assert_eq!(yaml_scalar("[x]", 0), "'[x]'");
        assert_eq!(yaml_scalar("{x: y}", 0), "'{x: y}'");
        assert_eq!(yaml_scalar("a #b", 0), "'a #b'");
        assert_eq!(yaml_scalar("a#b", 0), "a#b");
        assert_eq!(yaml_scalar(":start", 0), ":start");
        assert_eq!(yaml_scalar("-x", 0), "-x");
        assert_eq!(yaml_scalar("?x", 0), "?x");
        assert_eq!(yaml_scalar("-", 0), "'-'");
        assert_eq!(yaml_scalar("?", 0), "'?'");
        assert_eq!(yaml_scalar("你", 0), "你");
    }

    #[test]
    fn yaml_scalar_quotes_legacy_numeric_resolver_forms() {
        assert_eq!(yaml_scalar("1e-7", 0), "1e-7");
        assert_eq!(yaml_scalar("1.0e-7", 0), "'1.0e-7'");
        assert_eq!(yaml_scalar("1.0e-07", 0), "'1.0e-07'");
        assert_eq!(yaml_scalar("+1.0e-7", 0), "'+1.0e-7'");
        assert_eq!(yaml_scalar("-1.0e-7", 0), "'-1.0e-7'");
        assert_eq!(yaml_scalar("0b101", 0), "'0b101'");
        assert_eq!(yaml_scalar("-0b101", 0), "'-0b101'");
        assert_eq!(yaml_scalar("077", 0), "'077'");
        assert_eq!(yaml_scalar("0x10", 0), "'0x10'");
        assert_eq!(yaml_scalar("0o77", 0), "0o77");
        assert_eq!(yaml_scalar("0:01", 0), "0:01");
        assert_eq!(yaml_scalar("1:20", 0), "'1:20'");
    }

    #[test]
    fn yaml_scalar_matches_legacy_control_character_rendering() {
        assert_eq!(yaml_scalar("line\nbreak", 4), "'line\n\n      break'");
        assert_eq!(yaml_scalar("tab\tchar", 4), "\"tab\\tchar\"");
        assert_eq!(yaml_scalar("carriage\rreturn", 4), "\"carriage\\rreturn\"");
        assert_eq!(yaml_scalar("mix\n\t\r", 4), "\"mix\\n\\t\\r\"");
    }

    #[test]
    fn python_float_repr_matches_legacy_yaml_float_rendering() {
        assert_eq!(python_float_repr(1e-7), "1.0e-07");
        assert_eq!(python_float_repr(1e-6), "1.0e-06");
        assert_eq!(python_float_repr(1.23e-7), "1.23e-07");
        assert_eq!(python_float_repr(1e20), "1.0e+20");
        assert_eq!(python_float_repr(0.0001), "0.0001");
        assert_eq!(python_float_repr(120.0), "120.0");
    }
}
